### ISSUE TITLE
Allowed chars in SALT - [space]

### ISSUE THREAD

**Issue by scarpellini** [dlitz/python-pbkdf2#1]
I need to use space char (" ") in the 'salt' parameter (PBKDF2.crypt())  to generate a PBKDF2 key for an specific purpose. On my machine, I've already changed this code (line #271) and the tests has finished with status OK.

The line 271 became like that (space is the last char):
allowed = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789./ "

**Comment by dlitz** [comment]
Spaces are deliberately not allowed in the PBKDF2.crypt() format (which I made up).  You're not supposed to generate the salts yourself anyway.

If you are going to change the format, please also change the code so that the prefix is NOT "$p5k2$", as this creates interoperability problems with code that uses my format.

**Comment by dlitz** [comment]
To clarify, PBKDF2.crypt() is _only_ for password hashing, and it's not part of the PBKDF2 specification.  If you need general-purpose key derivation, don't use the crypt() function!

**Comment by scarpellini** [comment]
You have a point.
I was using 'crypt()' method in the past (project early days / first tests), but now I'm using only 'read()'. All that I need is just generate an 24bits key and just now I checked the code of this method (there are no references to 'crypt()' or to 'allowed') - Sorry!

Although I don't need to change the code anymore, I haven't found anything about the SALT characters validation in the RFC (http://www.ietf.org/rfc/rfc2898.txt).

Thank you.

**Comment by dlitz** [comment]
PBKDF2.crypt() isn't part of the RFC; it's just a convenience function that I made up to implement a crypt()-style password hash that uses PBKDF2.  I'm the one who came up with the format, and chose how the salt is represented.

Also, a 24-bit key is _waay_ too short for anything involving cryptography.  There are probably more bits of entropy in whatever passphrase you're using than in a 24-bit output.

**Comment by scarpellini** [comment]
K. I'm the client of this 'secure' channel. I have no choices about key format, key length or cryptography algorithms.
Thank u.
