### ISSUE TITLE
crypt() uses unexpected salt value

### ISSUE THREAD

**Issue by FrugalGuy** [dlitz/python-pbkdf2#3]
I think users expect `crypt("hi", "mom", iterations=1)` to return the hash value as the 192-bit PBKDF2 result for `PBKDF2("hi", "mom", iterations=1)` but it does not.
Instead, the actual salt value used in `crypt("hi", "mom", iterations=1)` is not "mom" but is rather the value "$p5k2$1$mom".

> b64encode(PBKDF2("hi", "mom", iterations=1).read(24),"./")
> '**dRUSa0XKUkjbqg5NOyaNy9t4F1fXTQ6T**'
> 
> crypt("hi", "mom", iterations=1)
> '$p5k2$1$mom$**7e7fV91gTM4ceXPmLUMU45GSLvyPc2Vt**'
> 
> b64encode(PBKDF2("hi", "**$p5k2$1$**mom", iterations=1).read(24),"./")
> '7e7fV91gTM4ceXPmLUMU45GSLvyPc2Vt'

patch starting at line 276 sends only the salt to PBKDF2() rather than the salt **plus** all the decoration that comes before it:

```
    if iterations is None or iterations == 400:
        iterations = 400
#        salt = "$p5k2$$" + salt
        rc = "$p5k2$$" + salt
    else:
#        salt = "$p5k2$%x$%s" % (iterations, salt)
        rc = "$p5k2$%x$%s" % (iterations, salt)
    rawhash = PBKDF2(word, salt, iterations).read(24)
#    return salt + "$" + b64encode(rawhash, "./")
    return rc + "$" + b64encode(rawhash, "./")
```

after patching you see the returned hash is the expected value:

> crypt("hi", "mom", iterations=1)
> '$p5k2$1$mom$**dRUSa0XKUkjbqg5NOyaNy9t4F1fXTQ6T**'

**Comment by dlitz** [comment]
Yes, that's the design.  Reasonable people may disagree about whether that was the optimal design, but I don't think it matters enough to justify introducing another incompatible scheme.  Today, I'd probably use scrypt, anyway.
